### ISSUE TITLE
Ensure module works with centos.

### ISSUE THREAD

**Issue by lliss** [zivtech/puppet-drupal-php#8]
The following block is causing issues on Centos and Debian environments:

https://github.com/zivtech/puppet-drupal-php/blob/master/manifests/init.pp#L60-L64

Alter this to switch based on the PHP version which might work on centos and debian systems.

The following might be suitable:

`if $::php_version == '' or versioncmp($::php_version, '5.5') >= 0 {`
this should get debian support back and removing  `provider => 'apt',` may provide centos support in some places.

**Comment by tizzo** [comment]
The only currently known issue is redis:

`if $::operatingsystemrelease >= '14.04' {`

This would be half-solved by replacing this with:

`if $::php_version == '' or versioncmp($::php_version, '5.5') >= 0 {`

**Comment by sk33lz** [comment]
The fix for this is merged and released on Puppet Forge as 3.2.1. Closing.
